# Generated by Django 6.0.5 on 2026-07-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jina la Kundi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='wifi', help_text='Mfano: wifi, phone, gift, clock (hizi zinatoka kwenye icon library yetu)', max_length=50, verbose_name='Picha ya Kundi (Icon Class)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio wa Kuonyesha')),
            ],
            options={
                'verbose_name': 'Kundi la Mabando',
                'verbose_name_plural': 'Makundi ya Mabando',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResellerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Halotel Bundle Reseller', max_length=100, verbose_name='Jina la Biashara')),
                ('whatsapp_number', models.CharField(help_text="Weka namba katika mfumo wa kimataifa bila '+' au '00'. Mfano: 255621234567", max_length=20, verbose_name='Namba ya WhatsApp')),
                ('welcome_message', models.TextField(default='Habari! Karibu kwenye duka letu la mabando ya Halotel ya bei nafuu na ya haraka sana. Chagua bando lako hapa chini kupata huduma.', verbose_name='Ujumbe wa Karibu (Hero Welcome)')),
                ('payment_instructions', models.TextField(default='Lipa kwa:\n1. HaloPesa: Lipa Namba (Till) 123456\n2. M-Pesa: Lipa Namba (Till) 654321\n\nBaada ya kulipia, oda yako itashughulikiwa mara moja na utapokea bando.', help_text='Maelekezo ya malipo yatakayoonyeshwa kwa mteja kabla ya kumuelekeza WhatsApp.', verbose_name='Maelekezo ya Malipo')),
                ('is_active_config', models.BooleanField(default=True, help_text='Hakikisha mpangilio mmoja tu ndio umechaguliwa kuwa Active.', verbose_name='Mpangilio Unaoingia Kazini (Active)?')),
            ],
            options={
                'verbose_name': 'Mpangilio wa Tovuti',
                'verbose_name_plural': 'Mipangilio ya Tovuti',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Bando')),
                ('price', models.PositiveIntegerField(verbose_name='Bei (TSH)')),
                ('validity', models.CharField(help_text='Mfano: Masaa 24, Siku 7, Siku 30', max_length=50, verbose_name='Muda wa Matumizi')),
                ('data_limit', models.CharField(blank=True, help_text='Mfano: 1.5 GB, 500 MB (Acha wazi kama hamna)', max_length=50, null=True, verbose_name='Kiasi cha Internet')),
                ('voice_limit', models.CharField(blank=True, help_text='Mfano: Dakika 100 Halo-Halo, Dakika 30 Mtandao Yote', max_length=50, null=True, verbose_name='Muda wa Kupiga')),
                ('sms_limit', models.CharField(blank=True, help_text='Mfano: SMS 100, SMS Bila Kikomo', max_length=50, null=True, verbose_name='Kiasi cha SMS')),
                ('description', models.TextField(blank=True, help_text='Maelezo ya ziada ya bando hili', null=True, verbose_name='Maelezo Mengineyo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bando Lipo Wazi?')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Bando Maarufu (Hot)?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Kuwekwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tarehe ya Kurekebishwa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bundles.bundlecategory', verbose_name='Kundi la Bando')),
            ],
            options={
                'verbose_name': 'Bando',
                'verbose_name_plural': 'Mabando',
                'ordering': ['price'],
            },
        ),
    ]
