# Generated by Django 6.0.5 on 2026-07-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['price'], 'verbose_name': 'Bando la Internet', 'verbose_name_plural': 'Mabando ya Internet'},
        ),
        migrations.AlterModelOptions(
            name='bundlecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Kundi la Muda', 'verbose_name_plural': 'Makundi ya Muda'},
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='sms_limit',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='voice_limit',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bundles.bundlecategory', verbose_name='Kundi la Muda'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='data_limit',
            field=models.CharField(default='1.5 GB', help_text='Mfano: 1.5 GB, 500 MB, 10 GB', max_length=50, verbose_name='Kiasi cha Internet'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada ya bando (Mfano: WhatsApp bure usiku, nk.)', null=True, verbose_name='Maelezo ya Ziada'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jina la Bando (Mfano: Internet 1.5GB)'),
        ),
        migrations.AlterField(
            model_name='bundlecategory',
            name='icon',
            field=models.CharField(default='wifi', help_text='Mfano: calendar-day, calendar-week, calendar-days (hizi ni icon za FontAwesome)', max_length=50, verbose_name='Picha ya Kundi (Icon Class)'),
        ),
        migrations.AlterField(
            model_name='bundlecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kundi la Muda (Mfano: Siku 1, Wiki 1, Mwezi 1)'),
        ),
    ]
