# Generated by Django 6.0.5 on 2026-07-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_alter_bundle_options_alter_bundlecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(unique=True, verbose_name='Subdomain (Mfano: juma)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Subdomain Ipo Wazi (Inafanya kazi)?')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Imelipiwa Mpaka Tarehe')),
                ('business_name', models.CharField(default='Halotel Bundle Reseller', max_length=100, verbose_name='Jina la Biashara')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Namba ya WhatsApp')),
                ('welcome_message', models.TextField(default='Habari! Karibu kwenye duka letu la mabando ya Halotel ya bei nafuu na ya haraka sana. Chagua bando lako hapa chini kupata huduma.', verbose_name='Ujumbe wa Karibu (Hero Welcome)')),
                ('payment_instructions', models.TextField(default='Lipa kwa:\n1. HaloPesa: Lipa Namba (Till) 123456\n2. M-Pesa: Lipa Namba (Till) 654321\n\nBaada ya kulipia, oda yako itashughulikiwa mara moja na utapokea bando.', verbose_name='Maelekezo ya Malipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Kuundwa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tarehe ya Kurekebishwa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL, verbose_name='Mmiliki (Mteja)')),
            ],
            options={
                'verbose_name': 'Mteja (Tenant)',
                'verbose_name_plural': 'Wateja (Tenants)',
            },
        ),
        migrations.DeleteModel(
            name='ResellerConfig',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada ya bando (Mfano: WhatsApp bure usiku, nk.)', null=True, verbose_name='Maeleze ya Ziada'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='bundles.tenant', verbose_name='Mteja (Tenant)'),
        ),
    ]
