# Generated by Django 6.0.7 on 2026-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_tenant_delete_resellerconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#ff6f00', max_length=7, verbose_name='Rangi Kuu (Hex)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#ffb300', max_length=7, verbose_name='Rangi ya Pili (Hex)'),
        ),
    ]
